// Generated by CoffeeScript 1.11.0
(function() {
  var entityMap, escapeHtml;

  entityMap = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': '&quot;',
    "'": '&#39;',
    "/": '&#x2F;'
  };

  escapeHtml = function(string) {
    return String(string).replace(/[&<>"'\/]/g, function(s) {
      return entityMap[s];
    });
  };

  $('p.p').each(function(_, li) {
    var html, i, j, key, len, result, trans, word;
    li = $(li);
    html = li.html().split(/\s+/);
    result = [];
    for (i = j = 0, len = html.length; j < len; i = ++j) {
      word = html[i];
      key = word.replace(/[,.;?…\s]/g, '').toLowerCase();
      trans = window.paliDict[key];
      if (trans) {
        result.push("<span class=\"p\" title=\"" + (escapeHtml(trans)) + "\">" + word + "</span>");
      } else {
        result.push("<span class=\"error\">" + word + "</span>");
      }
    }
    return li.html(result.join(' '));
  });

}).call(this);
