$.extend window.paliDict,
  "kiccho": "difficult, hard, rare, painful (nom)"
  "manussapaṭilābho": "human being + gaining (gaining of the human state)"
  "kicchaṃ": "difficult, hard, rare, painful (acc)"
  "maccānaṃ": "mortal beings (pl, gen, dat)"
  "jīvitaṃ": "life"
  "saddhammasavaṇaṃ": "true + Dhamma + hearing (hearing the true Dhamma)"
  "buddhānaṃ": "Buddhas (gen, dat)"
  "uppādo": "arising, birth"
  "sabbapāpassa": "all + evil (all evil)"
  "akaraṇaṃ": "non-doing"
  "kusalassa": "wholesome (gen, dat)"
  "upasampadā": "acquisition, attainment, entering"
  "sacittapariyodapanaṃ": "one's own + mind + cleaning (purification of one's own mind)"
  "etaṃ": "this"
  "buddhāna(ṃ)": "Buddhas (pl, gen, dat)"
  "sāsanaṃ": "teaching"
  "na": "not"
  "hi": "verily, indeed"
  "verena": "enmity, ill-will (inst)"
  "verāni": "enmities, ill-wills (nom, acc, voc)"
  "sammantīdha": "are pacified here"
  "kudācanaṃ": "any day, ever"
  "averena": "un-enmity (inst)"
  "sammanti": "they are pacified, they subside"
  "esa": "that"
  "dhammo": "Dhamma, truth"
  "sanantano": "eternal"
  "tīhi": "instrumental plural of ti, three"
  "aṃgehi": "factor, component, constituent part, limb, member (inst, abl)"
  "samannāgato": "endowed with, possessed of"
  "pāpaṇiko": "merchant, shopkeeper (nom)"
  "abhabbo": "incompetent, unable (nom)"
  "anadhigataṃ": "not find, not acquire (inf)"
  "bhogaṃ": "wealth (acc)"
  "adhigantuṃ": "find, acquire (inf)"
  "adhigataṃ": "obtained, acquired (inst)"
  "phātiṃ": "increase, development (acc)"
  "kātuṃ": "does (inf)"
  "katamehi": "which, what (pl, inst, abl)"
  "idha": "here, in the world"
  "pubbaṇhasamayaṃ": "in the forenoon, in the morning"
  "sakkaccaṃ": "properly, well, carefully, thoroughly"
  "kammantaṃ": "business, activity"
  "adhiṭṭhāti": "he attends to"
  "majjhaṇhikasamayaṃ": "during midday"
  "sāyaṇhasamayaṃ": "in the evening"
  "imehi": "by these"
  "kho": "emphatic particle"
  "evameva": "even so, thus, similarly, in like manner"
  "dhammehi": "factor, quality (pl, inst, abl)"
  "kusalaṃ": "virtue, good (action), merit"
  "samādhinimittaṃ": "object of meditation"
  "bhabbo": "competent, able (nom)"
  "pe": "signal of repetition"
  "appakā": "little, few"
  "te": "they"
  "sattā": "beings, living beings (pl, nom)"
  "manussesu": "men, human beings (pl, loc)"
  "ye": "which ones"
  "paccājāyanti": "are (re)born"
  "atha": "now, then"
  "ete'va": "these ones indeed"
  "bahutarā": "many, more"
  "aññatra": "outside"
  "manussehi": "men, human beings (pl, inst, abl)"
  "majjhimesu": "central, middle (pl, loc)"
  "janapadesu": "provinces, localities (pl, loc)"
  "paccantimesu": "bordering, adjoining (pl, loc)"
  "paññavanto": "wise ones, insightful persons (pl, nom)"
  "duppaññā": "not wise, foolish, stupid (pl, nom)"
  "jaḷā": "slow, stupid (pl, nom)"
  "ajalā": "not slow, not stupid (pl, nom)"
  "eḷamūgā": "not reciptive to the doctrine (pl, nom)"
  "aneḷamūgā": "reciptive to the doctrine (pl, nom)"
  "paṭibalā": "competent, capable (pl, nom)"
  "subhāsitadubbhāsitassa": "things well and badly spoken, things proper to say and not proper to say"
  "atthamaññatuṃ": "advantage, meaning + comprehends, discriminates (acc)"
  "ariyena": "noble, distinguished (inst)"
  "paññacakkhunā": "eye of wisdom (inst, abl)"
  "samannāgatā": "endowed with, possesed of (inst)"
  "avijjāgatā": "ignorant (nom, pl)"
  "sammūḷhā": "confused, confounded, stupid (nom, pl)"
  "labhanti": "they get, they receive"
  "dassanāya": "sight, seeing, insight (gen, dat, inst, abl)"
  "tathāgataṃ": "Tathagata (acc)"
  "tathāgatappaveditaṃ": "expounded by the Tathagata (acc)"
  "dhammavinayaṃ": "doctrine and discipline (acc)"
  "savaṇāya": "hearing, listening (gen, dat, inst, abl)"
  